with common_avg as (
	select avg(animation) as animation_glob_avg,
	   avg(adventure) as adventure_glob_avg,
	   avg(family) as family_glob_avg,
	   avg(comedy) as comedy_glob_avg,
	   avg(fantasy) as fantasy_glob_avg,
	   avg(romance) as romance_glob_avg,
	   avg(drama) as drama_glob_avg,
	   avg(action) as action_glob_avg,
	   avg(crime) as crime_glob_avg,
	   avg(thriller) as thriller_glob_avg,
	   avg(horror) as horror_glob_avg,
	   avg(history) as history_glob_avg,
	   avg(science_fiction) as science_fiction_glob_avg,
	   avg(mystery) as mystery_glob_avg,
	   avg(war) as war_glob_avg,
	   avg(music) as music_glob_avg,
	   avg(documentary) as documentary_glob_avg,
	   avg(western) as western_glob_avg,
	   avg(tv_movie) as tv_movie_glob_avg
	from user_genre_mapping
	where user_id in (select user_id from ratings where mid = 862)),
curr_avg as(select avg(rating) as local_avg from ratings where mid = 862),
population as (
	select 
		count(*) filter (where animation > (select genre_avg_rating from genre_info where genre_name = 'Animation')) as animation_count,
		count(*) filter (where family > (select genre_avg_rating from genre_info where genre_name = 'Family')) as family_count,
		count(*) filter (where history > (select genre_avg_rating from genre_info where genre_name = 'History')) as history_count,
		count(*) filter (where comedy > (select genre_avg_rating from genre_info where genre_name = 'Comedy')) as comedy_count, 
		count(*) filter (where documentary > (select genre_avg_rating from genre_info where genre_name = 'Documentary')) as documentary_count ,
		count(*) filter (where tv_movie > (select genre_avg_rating from genre_info where genre_name = 'TV Movie')) as tv_movie_count,
		count(*) filter (where fantasy > (select genre_avg_rating from genre_info where genre_name = 'Fantasy')) as fantasy_count,
		count(*) filter (where science_fiction > (select genre_avg_rating from genre_info where genre_name = 'Science Fiction')) as science_fiction_count,
		count(*) filter (where war > (select genre_avg_rating from genre_info where genre_name = 'War')) as war_count,
		count(*) filter (where music > (select genre_avg_rating from genre_info where genre_name = 'Music')) as music_count,
		count(*) filter (where horror > (select genre_avg_rating from genre_info where genre_name = 'Horror')) as horror_count,
		count(*) filter (where action > (select genre_avg_rating from genre_info where genre_name = 'Action')) as action_count,
		count(*) filter (where drama > (select genre_avg_rating from genre_info where genre_name = 'Drama')) as drama_count,
		count(*) filter (where crime > (select genre_avg_rating from genre_info where genre_name = 'Crime')) as crime_count,
		count(*) filter (where western > (select genre_avg_rating from genre_info where genre_name = 'Western')) as western_count,
		count(*) filter (where thriller > (select genre_avg_rating from genre_info where genre_name = 'Thriller')) as thriller_count,
		count(*) filter (where mystery > (select genre_avg_rating from genre_info where genre_name = 'Mystery')) as mystery_count,
		count(*) filter (where adventure > (select genre_avg_rating from genre_info where genre_name = 'Adventure')) as adventure_count,
		count(*) filter (where romance > (select genre_avg_rating from genre_info where genre_name = 'Romance')) as romance_count
	from user_genre_mapping where user_id in (
		select user_id from ratings where mid = 862
	) 
)

select 
	local_avg, 
	animation_glob_avg, 
	animation_count,
	adventure_glob_avg, 
	adventure_count,
	family_glob_avg, 
	family_count,
	comedy_glob_avg, 
	comedy_count,
	fantasy_glob_avg,
	fantasy_count,
	romance_glob_avg,
	romance_count,
	drama_glob_avg,
	drama_count,
	action_glob_avg,
	action_count,
	crime_glob_avg,
	crime_count,
	thriller_glob_avg,
	thriller_count,
	horror_glob_avg,
	horror_count,
	history_glob_avg,
	history_count,
	science_fiction_glob_avg,
	science_fiction_count,
	mystery_glob_avg,
	mystery_count,
	war_glob_avg,
	war_count,
	music_glob_avg,
	music_count,
	documentary_glob_avg,
	documentary_count,
	western_glob_avg,
	western_count,
	tv_movie_glob_avg,
	tv_movie_count
from common_avg, curr_avg, population
