apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: api-group8
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3333
          env:
            - name: STATIC_FILES_PATH
              value: /usr/src/app/ucl-imdb
            - name: PRODUCTION
              value: 'true'
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: postgres-username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: postgres-password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: postgres-db
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: backend-configmap
                  key: postgres_url
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-configmap
                  key: postgres_port
              # redis env variables
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: backend-configmap
                  key: redis_host
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-configmap
                  key: redis_port
            - name: CACHE_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  name: backend-configmap
                  key: cache_timeout
            - name: CACHE_MAX
              valueFrom:
                configMapKeyRef:
                  name: backend-configmap
                  key: cache_max
---
apiVersion: v1
kind: Service
metadata:
  name: api-external-service
spec:
  selector:
    app: api
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3333  # port on host
      targetPort: 3333
      nodePort: 30000
