apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          imagePullPolicy: Never
          image: postgres-group8
          ports:
            - containerPort: 5432
      # - resources:
      #     memory: "64Mi"
      #     cpu: "250m"
      #   limits:
      #     memory: "128Mi"
      #     cpu: "500m"
      # -env
      # - name: MONGO_INITDB_ROOT_USERNAME
      #   valueFrom:
      #     secretKeyRef:
      #       name: mongodb-secret
      #       key: mongo-root-username
      # - name: MONGO_INITDB_ROOT_PASSWORD
      #   valueFrom:
      #     secretKeyRef:
      #       name: mongodb-secret
      #       key: mongo-root-password
      # TODO: add env variables here, not Dockerfile
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
