apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        # imagePullPolicy: Never
        image: redis
        ports:
        - containerPort: 6379
        env:
        - name: REDIS_HOST
          valueFrom: 
            configMapKeyRef:
              name: backend-configmap
              key: redis_host
        - name: REDIS_PORT
          valueFrom: 
            configMapKeyRef:
              name: backend-configmap
              key: redis_port
        - name: CACHE_TIMEOUT
          valueFrom: 
            configMapKeyRef:
              name: backend-configmap
              key: cache_timeout
        - name: CACHE_MAX
          valueFrom: 
            configMapKeyRef:
              name: backend-configmap
              key: cache_max
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379

